### ISSUE TITLE
Dropdown not closed on click outside of ngSelect

### ISSUE THREAD

**Issue by malifai** [valor-software/ng2-select#230]
I have the problem, that the Dropdown does not close if i click outside the directive.
So basically i'm forced to select a value and delete it afterwards. 

It doesn't matter if i have one or multiple ngSelects in my view. 

I'm using the "multiple" type.

Any hints?

**Comment by NisStrom** [comment]
Yes this should be fixed as soon as possible. I created a pull request for that:
#251

**Comment by faizan-ali** [comment]
This is still an issue

**Comment by qoopa** [comment]
I halso have this issue when using 'multiple'. 

Does anyone have a workaround in the meantime?

**Comment by jamiec1234** [comment]
Any further work on this issue? Or any work arounds?

**Comment by jasonkrot** [comment]
The problem still exists. I just installed the plugin via npm, latest chrome on win10. The normal select also has this issue.

**Comment by ghost** [comment]
This is stil an issue. Any work around for this?

**Comment by meppiel** [comment]
I recently ran into the same issue, but only when running my app on iOS. For some reason the click event was not firing when a user had a ng2-select dropdown open and they clicked outside of it. As a temporary workaround, here's what I did:

- Installed hammerjs and hammer-timejs

- Imported both into my app.module.ts

- In my component.html, I added both a tap and a press event to my container

`<div class="container" (tap)="checkDropdowns($event)" (press)="checkDropdowns($event)">`

- Then in my component.ts, I simply checked the event's target to see if something outside of the ng2-select was clicked. If so, I just triggered the clickedOutside method:

`  checkDropdowns(event: any): void {

    var className = event.target.className.toLowerCase();

    if (className.indexOf('ui-select') > -1) {
      console.log('Something inside ng2-select was clicked');
      return;
    }

    if (event.target.parentElement && event.target.parentElement.parentElement) {
      className = event.target.parentElement.parentElement.className.toLowerCase();
      if (className.indexOf('ui-select') > -1) {
        console.log('A ng2-select option was clicked');
        return;
      }
    }

    let elementsToclose = this.selectElements.filter(function (el: any) {
      return el.optionsOpened == true;
    });

    elementsToclose.forEach(function (e: SelectComponent) {
      e.clickedOutside();
    })

  }`

It's ugly, but it works. :)

**Comment by Reddemonfox** [comment]
Hi, I got the same prob but for the time being I have done a quick hack to solve my problem.
Just use
[disabled]="isDisabledTrue"
(focusout)="removeData(item)"

in your element
where ,

removeData() {
const self = this;
self.isDisabledTrue = true;
setTimeout(() => {
self.isDisabledTrue = false;
}, 10);
}

This will handle both outside click situation and multiple ngSelect dropdown issue as well
