### ISSUE TITLE
can't select item when searching 

### ISSUE THREAD

**Issue by aldrindizonh** [valor-software/ng2-select#633]
I can't select text item when searching in the plugin. 

<img width="471" alt="screen shot 2017-02-03 at 1 19 08 pm" src="https://cloud.githubusercontent.com/assets/17155863/22580525/1f0e06d6-ea14-11e6-99be-f6695ac4d42c.png">

here is my code in html
                 ` <ng-select 
                              [items]="ticketOptionList.accountList"
                              (data)="refreshValueforAccount($event)"
                              (selected)="selectedAccount($event)"
                              [active] = "initialDataForAccount">
                      </ng-select>`

But when I click the item in blank area it will work

**Comment by khoanguyen2610** [comment]
Hi, i got this problem too. We need support.

**Comment by khoanguyen2610** [comment]
![hacked-searching ng2-select-mit](https://cloud.githubusercontent.com/assets/17254044/22678321/d57fd4a2-ed2b-11e6-8cd3-653ccf897233.png)
I found this problem, problem is HighlightPipe alway transform text, so we can't click on this test, we can click select outsite the label and then i fixed by my way.
In file select-pipe.jp, function HighlightPipe.prototype.transform, i added "return value;".
So it's not bold style when we searching but we can select result.

Expect MIT fix this issue. 
Thank you.

**Comment by elmartino** [comment]
+1

**Comment by rodneyjoyce** [comment]
I seem to have something similar -sometimes I can click on an item (without searching) and sometimes I cannot - it's a very frustrating user experience

**Comment by chaitrashivanand** [comment]
I am still getting this issue even after changing select-pipes.js.

**Comment by chaisangam** [comment]
We need support for this , please let us know if any one knows solution for this.

**Comment by jdelucaa** [comment]
+1
